[ssh]
host = "0.0.0.0"
port = "2222"

# Your company's logo is displayed as: [<logo>] <name>, with logo having 
# We suggest using a nerd font character for the logo.
[company]
name = "pausetta.org"
logo = ""
logo_bg = "purple" 
logo_fg = "fg" 
hide = false # if you don't like having the logo in the statusbar, just set this to true

[priorities]
crit = { value=10, color="red" } # requires IMMEDIATE attention 
high = { value=5, color="yellow" } # requires even more attention than usual
med = { value=3, color="cyan" } # requires more attention than usual
default = { value=1 } # standard issues. special priority that is applied by default when none is specified 
low = { value=0, color="black" } # worth considering only if you have extra time

# Labels that are added by default on project creation. Recommended to keep some "well defined" labels for common categories.
[[default_labels]] 
# anything that improves the project: new features, optimizations, refactorings...
name = "feat"
color = "blue"
symbol = "󰇈"

[[default_labels]]
# unexpected bugs or behaviours that pop up and need to be fixed. goes well with !crit...
name = "fix"
color = "red"
symbol = ""

[[default_labels]]
# anything that is required to do, but doesn't "touch" the code, eg. documentation, presentations, submissions, deadlines, advertisements...
name = "chore"
color = "green"
symbol = "󰃢"

# Groups that are added by default when creating a new project
[[default_groups]]
name = "admins"
color = "red"
mentionable = false
permissions = ["write-issues", "read-issues", "edit-project", "delete-project"]
add_creator = true # if true, the creator of the project will be automatically added to this group.
                   # at least one group has to have this, or else the creator won't be a member of the project.

[[default_groups]]
name = "devs"
mentionable = false
permissions = ["write-issues", "read-issues"]

[[default_groups]]
name = "guests"
mentionable = false
permissions = ["read-issues"]
